// DATA CONSTANT

// PARTICULAR
export const INFO_PARTICULAR = "INFO_PARTICULAR";
export const SCHEMA_PARTICULAR = "SCHEMA_PARTICULAR";
export const UPDATE_INFO_PARTICULAR = "UPDATE_INFO_PARTICULAR";
export const UPDATE_INFO_PARTICULAR_CLEAN = "UPDATE_INFO_PARTICULAR_CLEAN";

// COMPANY
export const INFO_COMPANY = "INFO_COMPANY";
export const SCHEMA_COMPANY = "SCHEMA_COMPANY";
export const UPDATE_INFO_COMPANY = "UPDATE_INFO_COMPANY";
export const UPDATE_INFO_COMPANY_CLEAN = "UPDATE_INFO_COMPANY_CLEAN";

// USER
export const INFO_USER = "INFO_USER";
export const UPDATE_INFO_USER= "UPDATE_INFO_USER";

